language: node_js
node_js:
- '4.1'
before_install:
- sudo apt-get install expect
- openssl aes-256-cbc -K $encrypted_32270c5e578a_key -iv $encrypted_32270c5e578a_iv
  -in .travis/dokku_deploy_key.enc -out .travis/dokku_deploy_key -d
before_script:
- npm run third-party-dependencies
deploy:
  skip_cleanup: true
  provider: script
  script: bash scripts/travis_deploy.sh
  on:
    branch: master
