language: node_js
node_js:
- '4.1'
before_install:
- openssl aes-256-cbc -K $encrypted_32270c5e578a_key -iv $encrypted_32270c5e578a_iv
  -in ssh_keys.tar.enc -out ssh_keys.tar -d
- sudo apt-get install expect
- tar xvf ssh_keys.tar
before_script:
- npm run third-party-dependencies
deploy:
  skip_cleanup: true
  provider: script
  script: bash scripts/travis_deploy.sh
  on:
    branch: master
