language: node_js
node_js:
- '4.1'
before_install:
- sudo apt-get install expect
before_script:
- npm run third-party-dependencies
deploy:
  skip_cleanup: true
  provider: script
  script: bash scripts/travis_deploy.sh
  on:
    branch: master
